### ISSUE TITLE
Backup tailer doesn't like trace-level logging

### ISSUE THREAD

**Issue by Kaiede** [edward3h/minecraft-webhook#14]
The backup container has some verbosity settings that affect the logging a little, and it breaks the regex being used for the tailer which expects to match the end of the line explicitly: "Backed up as: (.+\\.mcworld)$". 

So the line can be either one of these:
"[08:27:15.820][info    ] Backed up as: Wakanda.20220623-082715.mcworld"
"[08:27:15.820][info    ] Backed up as: Wakanda.20220623-082715.mcworld (ContainerConnection.swift:132)"

Most folks shouldn't see the latter, but since I always leave my logging on high for diagnostic purposes while making changes, it reveals the breaking behavior.

**Comment by edward3h** [comment]
Good to know. We can remove the line end match.

**Comment by edward3h** [comment]
I published 0.4.2 with the fix for this.
